// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD02re3zyTlu4Jc47ocGpiAIpTZ5RFyVIM',
    appId: '1:521207039638:web:c0c53d7287646f0952a4b7',
    messagingSenderId: '521207039638',
    projectId: 'plis-d5a15',
    authDomain: 'plis-d5a15.firebaseapp.com',
    storageBucket: 'plis-d5a15.firebasestorage.app',
    measurementId: 'G-MSTBJLJCFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK3Xnt43_qtM8fgpdsRfDYcaGxhlR70TA',
    appId: '1:609107762959:android:d077e094b2cc53f2a3a87a',
    messagingSenderId: '609107762959',
    projectId: 'plis-b0c7c',
    storageBucket: 'plis-b0c7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpmn7X2KglhVILPpMNi8mYoJ6lEEE0q0',
    appId: '1:609107762959:ios:b15f72c1300523d7a3a87a',
    messagingSenderId: '609107762959',
    projectId: 'plis-b0c7c',
    storageBucket: 'plis-b0c7c.firebasestorage.app',
    iosBundleId: 'com.example.plisConductorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHqZw46AzoKGl9fC9QW08fqXZ2zMkBUMk',
    appId: '1:521207039638:ios:e0b37d024624559652a4b7',
    messagingSenderId: '521207039638',
    projectId: 'plis-d5a15',
    storageBucket: 'plis-d5a15.firebasestorage.app',
    iosBundleId: 'com.example.plisConductorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlW8mJiBsR5UwHw8bmg2OsJQPSoFGx8s',
    appId: '1:609107762959:web:5edc24eb507d76c5a3a87a',
    messagingSenderId: '609107762959',
    projectId: 'plis-b0c7c',
    authDomain: 'plis-b0c7c.firebaseapp.com',
    storageBucket: 'plis-b0c7c.firebasestorage.app',
  );

}